apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planb438/git-ops.git
    targetRevision: HEAD
    path: odoo-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: odoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true